### PR TITLE
Added Pygments install (optional)

### PR DESCRIPTION
**Pull request by Tom32i**
See: http://gohugo.io/extras/highlighting/

### CODE REVIEW

**Comment by benji07** [comment]
:+1:

**Comment by nervo** [comment]
hmm, we already have a pip role, i would prefer to have a note in the readme. Something like "If you would like pygments, please use the appropriate role + example + bisous"

**Comment by hyvs** [comment]
Can you update readme "Role Variables" ?

**Comment by nervo** [comment]
Anyway, :+1: :)

**Pull request closed without merging**
